### ISSUE TITLE
Wykresy ggplot

### ISSUE THREAD

**Issue by piotrb5e3** [piotrb5e3/DataProducts#10]
Potrzebna jest funkcja, która otrzymuje data.frame z wynikami matur, data.frame z opisem szkół, nazwę kolumny z data.frame wyników i id szkoły, a produkuje histogram/wykres gęstości:
-na pierwszym planie jaskrawym kolorem dla wybranej szkoły
-na drugim planie pastelowym kolorem dla gminy
-w tle, szarym kolorem, dla całego kraju

**Comment by AdriannaTr** [comment]
http://pastebin.com/jxEa9S5S
